version: '3.7'

services:
  app:
    container_name: app
    build: 
      context: .
      dockerfile: ./docker/dev/images/app/Dockerfile
    restart: always
    env_file:
     - ./.env
    depends_on:
      - nginx
      - postgres
      - rabbitmq
    ports:
      - 3000:3000

  app-queue:
    container_name: app-queue
    build: 
      context: .
      dockerfile: ./docker/dev/images/app-queue/Dockerfile
    restart: always
    env_file:
     - ./.env
    depends_on:
      - rabbitmq

  nginx:
    container_name: nginx
    build: 
      context: .
      dockerfile: ./docker/dev/images/nginx/Dockerfile
    restart: always
    ports:
      - 8000:8000

  postgres:
    build: ./docker/dev/images/postgres
    container_name: postgres-dev
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_HOST_AUTH_METHOD: "scram-sha-256"
      POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256 --auth-local=scram-sha-256"
    volumes:
      - ./scripts/dev/postgres/init.sh:/docker-entrypoint-initdb.d/init.sh
      - postgres_data:/var/lib/postgresql/data
    restart: always
    ports:
      - 5432:5432

  rabbitmq:
    build: ./docker/dev/images/rabbitmq
    container_name: rabbitmq-dev
    environment:
      RABBITMQ_DEFAULT_USER: "admin"
      RABBITMQ_DEFAULT_PASS: "admin"
    restart: always
    ports:
      - 5672:5672
      - 15672:15672

volumes:
  postgres_data: {}