FROM postgres:14-alpine

LABEL maintainer="Gabriel Ferrari Tarall Ferraz"

ENV POSTGRES_DEV_DB clean_onboarding_postgres_dev_db
ENV POSTGRES_DEV_USER dev_user
ENV POSTGRES_DEV_PASSWORD dev_user

ENV POSTGRES_MAX_CONNECTIONS 10