name: Application API Build

on:
  push:
    branches: [ "main", "release" ]
  pull_request:
    branches: [ "main", "release" ]

jobs:
  initialize-app:
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        node: [ 18 ]
    name: Cache Node dependencies
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          
      - name: Install Packages
        run: |
          cd backend
          npm i
          
      - name: Cache Node Modules
        uses: actions/cache@v3.2.3
        with:
          path: ./backend/node_modules
          key: node-modules-app-cache-key
          
      - name: Cache package-lock.json
        uses: actions/cache@v3.2.3
        with:
          path: ./backend/package-lock.json
          key: package-lock-app-cache-key

  test-and-lint:
    runs-on: ubuntu-latest
    needs: initialize-app
    if: ${{ (github.ref == 'refs/heads/release' || github.ref == 'refs/heads/main') }}
    strategy:
      matrix: 
        node: [ 18 ]
    name: Test And Linting NodeJS v${{ matrix.node }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: Use Cached Node Modules
        uses: actions/cache@v3.2.3
        with:
          path: ./backend/node_modules
          key: node-modules-app-cache-key
          
      - name: Use Cached package-lock.json
        uses: actions/cache@v3.2.3
        with:
          path: ./backend/package-lock.json
          key: package-lock-app-cache-key

      - name: Linting
        run: |
          cd backend
          npm run linting

      - name: Testing
        run: |
          cd backend
          npm run test

  validate-terraform:
    runs-on: ubuntu-latest
    needs: initialize-app
    if: ${{ (github.ref == 'refs/heads/release' || github.ref == 'refs/heads/main') }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.7
    
      - name: Validate Terraform
        run: |
          cd backend/deploy
          terraform init -backend=false
          terraform validate

  build-and-push:
    runs-on: ubuntu-latest
    needs: [ test-and-lint, validate-terraform ]
    if: ${{ (github.ref == 'refs/heads/release' || github.ref == 'refs/heads/main') }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

  staging-plan:
    runs-on: ubuntu-latest
    needs: build-and-push
    if: ${{ (github.ref == 'refs/heads/release' || github.ref == 'refs/heads/main') }}
    steps:
      - name: Staging Plan
        run: |
          echo "Staging Plan"

  staging-apply:
    runs-on: ubuntu-latest
    needs: staging-plan
    if: ${{ (github.ref == 'refs/heads/release' || github.ref == 'refs/heads/main') }}
    steps:
      - name: Staging Apply
        run: |
          echo "Staging Apply"

  production-plan:
    runs-on: ubuntu-latest
    needs: build-and-push
    if: ${{ github.ref == 'refs/heads/main' }}
    steps:
      - name: Prouction Plan
        run: |
          echo "Production Plan"

  production-apply:
    runs-on: ubuntu-latest
    needs: production-plan
    if: ${{ github.ref == 'refs/heads/main' }}
    steps:
      - name: Production Apply
        run: |
          echo "Production Apply"

  staging-destroy:
    runs-on: ubuntu-latest
    needs: staging-apply
    if: ${{ (github.ref == 'refs/heads/release' || github.ref == 'refs/heads/main') }}
    steps:
      - name: Destroy Staging
        run: |
          echo "Run Terraform to destroy staging"

  production-destroy:
    runs-on: ubuntu-latest
    needs: production-apply
    if: ${{ github.ref == 'refs/heads/main' }}
    steps:
      - name: Destroy Production
        run: |
          echo "Run Terraform to destroy production"
